services:
  traefik:
    image: traefik:v3.1
    ports:
      - "80:80" # HTTP
      - "8080:8080" # traefik dashboard + API
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml
