log:
  level: DEBUG

accessLog: {}

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

api:
  insecure: true # activate API directly on the traefik entryPoint

providers:
  docker:
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true
